name: Nicole Dominguez
description: Nicole Dominguez's Portfolio and Playground
url: http://nicoledominguez.com
markdown: redcarpet
pygments: true
permalink: /:categories/:title
timezone: America/New_York
exclude: ['Rakefile', 'config.rb', 'README.md','gems']
include: ['.htaccess', '.htpasswd']