name: Nicole Dominguez
description: Nicole Dominguez's Portfolio and Playground
url: http://nicoledominguez.com
markdown: redcarpet
highlighter: true
permalink: /:categories/:title
timezone: America/New_York
exclude: ['config.rb', 'README.md','gems','Gemfile','Guardfile', '.DS_Store']
include: ['.htaccess', '.htpasswd']

rdiscount:
    extensions: [smart]

sass:
    sass_dir: _site/assets/sass
    css_dir: _site/assets/stylesheets
    output_style: compact
    line_comments: false

# Plugin: jekyll-assets
assets:
  sources:
    - assets/sass
    - assets/stylesheets
    - assets/images

  css_compressor: sass
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
