name: Nicole Dominguez
description: Nicole Dominguez's Portfolio and Playground
url: http://nicoledominguez.com
markdown: redcarpet
pygments: true
permalink: /:categories/:title
timezone: America/New_York
exclude: ['config.rb', 'README.md','gems','Gemfile','Guardfile']
include: ['.htaccess', '.htpasswd']

rdiscount:
    extensions: [smart]

sass:
    sass_dir: _site/assets/sass
    css_dir: _site/assets/stylesheets
    output_style: compact
    line_comments: false